name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

env:
  DOCKERHUB_SLUG: crazymax/goxx
  GHCR_SLUG: ghcr.io/crazy-max/goxx
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      -
        name: Cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: /tmp/.goxx-cache
          key: ${{ runner.os }}-goxx-base-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-goxx-base-
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      -
        name: Build base (cache only)
        uses: docker/bake-action@5be5f02ff8819ecd3092ea6b2e6261c31774f2b4 # v6.10.0
        with:
          targets: base
          set: |
            *.platform=${{ env.PLATFORMS }}
            *.cache-from=type=gha,scope=base
            *.cache-to=type=gha,scope=base,mode=max

  build:
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: read # same as global permissions
      packages: write # required to push to GHCR
    env:
      LATEST_CURRENT: 1.25.1
      LATEST_PREVIOUS: 1.24.7
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.24.0
          - 1.24.1
          - 1.24.2
          - 1.24.3
          - 1.24.4
          - 1.24.5
          - 1.24.6
          - 1.24.7
          - 1.25.0
          - 1.25.1
    steps:
      -
        name: Remove dotnet
        run: sudo rm -rf /usr/share/dotnet
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      -
        name: Tags
        id: tags
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          result-encoding: string
          script: |
            const os = require('os');
            const majorMinor = "${{ matrix.go_version }}".match(/[0-9]+\.[0-9]+/g)[0];
            const tags = ["${{ matrix.go_version }}"];
            switch ("${{ matrix.go_version }}") {
              case "${{ env.LATEST_CURRENT }}": {
                tags.push(majorMinor, "latest");
                break;
              }
              case "${{ env.LATEST_PREVIOUS }}": {
                tags.push(majorMinor);
                break;
              }
            }
            return tags.join(os.EOL);
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: |
            ${{ env.DOCKERHUB_SLUG }}
            ${{ env.GHCR_SLUG }}
          tags: ${{ steps.tags.outputs.result }}
          labels: |
            org.opencontainers.image.title=goxx (go-${{ matrix.go_version }})
            org.opencontainers.image.vendor=CrazyMax
      -
        name: Login to DockerHub
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Login to GHCR
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build goxx
        uses: docker/bake-action@5be5f02ff8819ecd3092ea6b2e6261c31774f2b4 # v6.10.0
        with:
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file }}
          targets: image
          set: |
            *.platform=${{ env.PLATFORMS }}
            *.args.GO_VERSION=${{ matrix.go_version }}
            *.cache-from=type=gha,scope=base
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
